[2023-10-02] dohyun #296
RecoRecoNi/Algorithm-Study pull request #306
Opened 2023-10-01 19:30 UTC by limstonestone

### PR Summary

풀이시간
- 약 1시간 풀이 후 실패로 답지 참조

접근법
- N 10만 이하 -> O(NlogN)
- 이전에 풀었던 문제에서 스택으로 시간 여행을 하던게 기억남! 큐로도 구현은 할 수 있을 것 같다
    - 를 시도하다가 더 과거의 인덱스도 저장해야하는 등 생각보다 복잡함에 포기...
- 답지 풀이
    - 단순 이중반복문으로 구현
    - 비슷하게 생각은 해본 풀이지만 O(N^2) 풀이라 접음 -> 왜 통과하는거지 ..???

회고
- 상수시간을 최대한 줄이는 문제도 존재하는듯하다
    - 빠르게 구현할수있는 풀이가 생각난다면 우선 구현하여 제출해보는 것도 나쁘지 않은 전략인듯 함

### ISSUE NUMBER

- #296

2023-10-03 10:43 UTC, zsmalla approved these changes
도현님께서 구현하신 로직에서 스택이나 큐를 활용한다면 어렵지 않게 도입하실 수 있으실 것 같아요! 인덱스의 차를 활용하는 방식이 거의 동일하거든요!

2023-10-03 10:43 UTC, zsmalla commented on Programmers/주식가격/dohyun.py
> +    - 비슷하게 생각은 해본 풀이지만 O(N^2) 풀이라 접음 -> 왜 통과하는거지 ..???
저도 풀이를 참고했을 때 여러 풀이가 이 중 반복문으로 해결해도 풀린다고 하더라구요! 저는 문제의 주제가 스택/큐였기 때문에 스택으로 접근해보긴 했습니다!

2023-10-04 02:07 UTC, ksumini approved these changes

2023-10-04 02:07 UTC, ksumini commented on Programmers/주식가격/dohyun.py
> +    - 비슷하게 생각은 해본 풀이지만 O(N^2) 풀이라 접음 -> 왜 통과하는거지 ..???
이 문제자체가 그냥 테케가 부실한거 같아요 😐 효율성 통과하는게 말이 안되는데 프로그래머스에 이런 문제들 몇 개 있더라구요..
원래 도현님이 처음 생각하신 것처럼 O(N^2)은 통과가 안되는게 맞아요!

2023-10-04 02:16 UTC, ksumini requested changes

2023-10-04 02:16 UTC, ksumini commented on Programmers/주식가격/dohyun.py
> +- 상수시간을 최대한 줄이는 문제도 존재하는듯하다
아니에요 이 문제는!!
만약에 최악의 경우 prices = [2, 3, 4, 5, 6, 7, 8, ..., 100000]처럼 오름차순돼있다고 했을 때
저 이중 for문 코드대로라면, O(n^2)이 될 수 있으니까
도현님이 처음에 생각하신것처럼 이 풀이는 사실 틀린 풀이에요 😥
stack으로 다시 생각해보세요~!! #241 이 문제랑 비슷해요!

2023-10-07 15:17 UTC, Woo-Yeol approved these changes
도현님의 고민의 흔적이 너무 공감되어서 볼 때 리뷰보다는 공감을 하게 되었던 것 같네요 ㅎㅎ 고생하셨습니다 도현님!

2023-10-07 15:17 UTC, Woo-Yeol commented on Programmers/주식가격/dohyun.py
> +    - 비슷하게 생각은 해본 풀이지만 O(N^2) 풀이라 접음 -> 왜 통과하는거지 ..???
저도 그랬습니다! 전 문제 조건 잘못보고 deque으로 시뮬레이션처럼 구현했었는데요 풀리고 주석쓰다가 당황했습니다 ㅋㅋㅋㅋㅋ 그래서 혹시 가지치기가 좀 많이 됐나? 생각했다가 stack 풀이를 찾아봤네요 ㅎㅎ

2023-10-07 15:17 UTC, Woo-Yeol commented on Programmers/주식가격/dohyun.py
> +        # 가격이 끝까지 떨어지지 않은 경우
동일한 피드백입니다만 가격이 끝까지 떨어지지 않은 경우를 미리 정의하고 진행해도 좋을 것 같아요!

```
# answer를 max 값으로 초기화
# ex) [1,2,3,2,3] -> [4,3,2,1,0]
answer = [v for v in range(len(prices)-1, -1, -1)]
```

2023-10-09 01:22 UTC, merged